# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  api_token: <%= ENV["API_TOKEN"] %>

  nexmo_api_key: <%= ENV["NEXMO_API_KEY"] %>
  nexmo_api_secret: <%= ENV["NEXMO_API_SECRET"] %>

development:
  <<: *common
  secret_key_base: 30447fa2678398a12f693387814909edcf07980bc707adc4cc3102c53a69a50e91f0496a1197a8981d32e3f4c3d34a8c75b7822b6e61b36c982484f90ed16369

test:
  <<: *common
  secret_key_base: c1531dbd77532a69a25974842003d2ca65c4c19775d9f312df152c34079d4c167ba539f87b010445174f666962a03756afe49c37548bf1f262dd39179993af69
  api_token: "test_token"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
